export const PFE_FETCH_REQUEST = 'PFE_FETCH_REQUEST';
export const PFE_FETCH_SUCCESS = 'PFE_FETCH_SUCCESS';
export const PFE_FETCH_FAIL = 'PFE_FETCH_FAIL';

export const PFE_CREATE_REQUEST = 'PFE_CREATE_REQUEST';
export const PFE_CREATE_SUCCESS = 'PFE_CREATE_SUCCESS';
export const PFE_CREATE_FAIL = 'PFE_CREATE_FAIL';

export const PFE_UPDATE_STATUS_REQUEST = 'PFE_UPDATE_STATUS_REQUEST';
export const PFE_UPDATE_STATUS_SUCCESS = 'PFE_UPDATE_STATUS_SUCCESS';
export const PFE_UPDATE_STATUS_FAIL = 'PFE_UPDATE_STATUS_FAIL';
