export const USERS_FETCH_REQUEST = 'USERS_FETCH_REQUEST';
export const USERS_FETCH_SUCCESS = 'USERS_FETCH_SUCCESS';
export const USERS_FETCH_FAIL = 'USERS_FETCH_FAIL';

export const USER_CREATE_REQUEST = 'USER_CREATE_REQUEST';
export const USER_CREATE_SUCCESS = 'USER_CREATE_SUCCESS';
export const USER_CREATE_FAIL = 'USER_CREATE_FAIL';

export const USER_UPDATE_REQUEST = 'USER_UPDATE_REQUEST';
export const USER_UPDATE_SUCCESS = 'USER_UPDATE_SUCCESS';
export const USER_UPDATE_FAIL = 'USER_UPDATE_FAIL';

export const USER_FETCH_BY_EMAIL_REQUEST = 'USER_FETCH_BY_EMAIL_REQUEST';
export const USER_FETCH_BY_EMAIL_SUCCESS = 'USER_FETCH_BY_EMAIL_SUCCESS';
export const USER_FETCH_BY_EMAIL_FAIL = 'USER_FETCH_BY_EMAIL_FAIL';
